project:
  type: website

website:
  title: "ISSS608-VAA-GroupProject"
  navbar:
    right:
      - href: about.qmd
        text: About
        
      - text: "Team"
        menu:
          - text: "Project Proposal"
            href: Visual Analytics Project/Team/Project_Proposal.html
            
          - text: "Minutes of Meetings" 
            href: Visual Analytics Project/Team/Minutes_of_Meetings.html
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

