project:
  type: website

website:
  favicon: img/logo2.png
  navbar:
    logo: img/logo.png
    background: "transparent"
    foreground: "#ffff"
    right:
      - text: "Proposal"
        href: Team/Project_Proposal.qmd
      - text: "Prototype"
        menu:
          - text: "Storyboard"
            href: prototype/storyboard.html
      - text: "Team"
        menu:
          - href: about.qmd
            text: "About Us"
          - text: "Minutes of Meetings" 
            href: Team/Minutes_of_Meetings/MM_Page.html
      - text: "Shiny App"
        menu:
          - href: about.qmd
            text: "User Guide"
          - href: https://evangelineolivia.shinyapps.io/ShinyApp/
            text: "Shiny App"
  page-footer: 
    background: "transparent"
    foreground: "black"
    left: "ISSS 608 Project" 
    right: 
      - icon: github
        href: https://github.com/xinyi-ux/Visual-Analytics-Project
format:
  html:
    theme: default
    css: styles.css
    toc: true
    number-sections: true

editor: visual

