project:
  type: website

website:

  navbar:
    title: "From Folk to Fame"
    background: "transparent"
    foreground: "#ffff"
    right:
      # - href: about.qmd
      #   text: "Overview"
        
      - text: "Prototype"
        menu:
          - text : " "
      
      - text: "Team"
        menu:
          - text: "Project Proposal"
            href: Team/Project_Proposal.html
          - text: "Minutes of Meetings" 
            href: Team/Minutes_of_Meetings/MM_Page.html
  page-footer: 
    background: "transparent"
    foreground: "black"
    left: "ISSS 608 Project" 
    right: 
      - icon: github
        href: https://github.com
format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

