---
title: "Minutes of Meetings 2"
date: 2025-06-05
author: Evangeline Olivia, Patricia Trisno, Xu Xinyi
format: 
  html:
    number-sections: false
body-classes: others
---

# ISSS608 Group 10 - Project Meeting Minutes

### Minutes of Team Meeting

**Date :** Sunday, 2nd June 2025

**Time :** 10:30am-11:30am

**Present:**

-   Evangeline Olivia Sidiharto Kusumoputri

-   Patricia Trisno

-   Xu, Xinyi

### Agenda Items

1.  **Module Prototyping Progress Review**

**Action**: 
Each member shared updates on the module they are individually developing as part of the Mini-Challenge 1 prototype.

**Discussion**:

-   All members confirmed progress in module coding and visualization.

-   Xinyi focused on implementing temporal influence dynamics using centrality scores over time.

-   Evangeline explored artists in the network and used a scoring system based on their collaborations, creative roles, and charted works to predict which ones are most likely to become rising stars.

-   Patricia explored visualizing collaboration density and node degree for genre evolution tracking.

**Outcome**: 
Modules are progressing well, and all team members are on track to finalize them before integration.

2. **Shiny App Integration Planning**

**Action**: 
Planned how individual prototype modules will be integrated into the final Shiny application.

**Discussion**:

- Agreed to use a tab-based interface where each tab represents one analytical module.

- Decided to define shared data inputs at the global level (server.R) and reuse across modules.

- Discussed standardizing visual styling and color palettes for a consistent interface.

**Outcome**: 
Integration strategy confirmed. Final modules will be modularized using `moduleServer()` and `UI()` structure for Shiny compatibility.

3. **Set up a shared Git repository for version control and backup.**

**Next Steps**

- Finalize  each module individually.
- Begin layout design of the poster over the weekend.
- Schedule dry run of full Shiny app by 10th June.

**Next Meeting Scheduled**: Monday, 16th June (7:00 pm – 8:00 pm)